name: ea_connect
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  cupertino_icons: ^1.0.8

   # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Logo.png
    - assets/proyecto1.jpg
    - assets/proyecto2.jpg
    - assets/proyecto3.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Logo.png"